"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import '@interchain-ui/react/styles';
import { ChainProvider } from '@cosmos-kit/react';
import { chains, assets } from 'chain-registry';
// import { wallets } from '@cosmos-kit/keplr';
import { SignerOptions, wallets } from 'cosmos-kit';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChainProvider
          chains={chains} // supported chains
          assetLists={assets} // supported asset lists
          wallets={wallets} // supported wallets
          // walletConnectOptions={...} // required if `wallets` contains mobile wallets
          walletConnectOptions={{
            signClient: {
              projectId: 'a8510432ebb71e6948cfd6cde54b70f7',
              relayUrl: 'wss://relay.walletconnect.org',
              metadata: {
                name: 'CosmosKit Template',
                description: 'CosmosKit dapp template',
                url: 'https://docs.cosmology.zone/cosmos-kit/',
                icons: [],
              },
            },
          }}
          >
          {children}
        </ChainProvider>
      </body>
    </html>
  );
}
